In [1]:
%matplotlib inline 
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

In [5]:
traffic_stations = pd.read_csv('/Users/erikrood/desktop/traffic_counting_stations.csv', error_bad_lines=False) 
#traffic_counts = pd.read_csv('/Users/erikrood/desktop/iPython_datasets/hourly_traffic_counts.csv')

In [6]:
traffic_stations.head()

,Year_Record,State_Code,Station_Id,Travel_Dir,Travel_Lane,F_System,Num_Lanes,Sample_Type_Volume,Num_Lanes_Volume,Method_Volume,...,NHS,Posted_Route_Signing,Posted_Signed_Route,Con_Route_Signing,Con_Signed_Route,Station_Location,Class_Change_Date,Class14_distribution,Class15_distribution,New_FSystem
0,2015,2,101,1,1,1,1,T,1,3,...,1,3,3,NaN,NaN,PARKS HIGHWAY AT CHULITNA - NB,NaN,NaN,NaN,1
1,2015,2,101,5,1,1,1,T,1,3,...,1,3,3,NaN,NaN,PARKS HIGHWAY AT CHULITNA - SB,NaN,NaN,NaN,1
2,2015,2,102,1,1,1,2,T,2,3,...,1,3,1,NaN,NaN,GLENN HIGHWAY - SOUTH OF KINGS,NaN,0,NaN,0
3,2015,2,102,1,2,1,2,T,2,3,...,1,3,1,NaN,NaN,GLENN HIGHWAY - SOUTH OF KINGS,NaN,0,NaN,0
4,2015,2,102,5,1,1,2,T,2,3,...,1,3,1,NaN,NaN,GLENN HIGHWAY - SOUTH OF KINGS,NaN,0,NaN,0